/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/storages/pre-authenticated-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pre-Authenticated Url 발급
         * @description OCI Object Storage에 파일 업로드를 위한 Pre-Authenticated Url을 발급합니다.
         */
        post: operations["getPreAuthenticatedUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 예제 데이터 목록 조회
         * @description 모든 예제 데이터를 조회합니다.
         */
        get: operations["getAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/examples/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 예제 데이터 단건 조회
         * @description ID로 특정 예제 데이터를 조회합니다.
         */
        get: operations["getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponsePreAuthenticatedUrlResponse: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            result?: components["schemas"]["PreAuthenticatedUrlResponse"];
        };
        PreAuthenticatedUrlResponse: {
            url?: string;
        };
        ApiResponseListExampleRes: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            result?: components["schemas"]["ExampleRes"][];
        };
        /** @description 예제 응답 DTO */
        ExampleRes: {
            /**
             * @description 예제 이름
             * @example 샘플 예제
             */
            name?: string;
        };
        ApiResponseExampleRes: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            result?: components["schemas"]["ExampleRes"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPreAuthenticatedUrl: {
        parameters: {
            query: {
                /**
                 * @description 버킷에 업로드할 파일 이름 및 경로
                 * @example profile/{username}.jpg
                 */
                fileName: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePreAuthenticatedUrlResponse"];
                };
            };
        };
    };
    getAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListExampleRes"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 조회할 예제 ID
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExampleRes"];
                };
            };
        };
    };
}
